apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chirpstack-cm1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default