apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresqldata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: postgres-storage-class
