apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresqldata
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: us-chirpstack-postgres-pv