apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresqldata
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  csi:
    driver: disk.csi.azure.com
    volumeHandle: "/subscriptions/1e4e3cbd-99c6-4435-94f1-a2e7106eefc1/resourceGroups/PowerPlatform-IOTReporting-dev/providers/Microsoft.Compute/disks/us-postgresql-data"  # Disk ID
    fsType: ext4
  mountOptions:
    - dir_mode=0750
    - file_mode=0750
    - uid=999
    - gid=999
