apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresqldata
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  volumeName: postgresqldata
  resources:
    requests:
      storage: 1Gi
