apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresqldata
  namespace: default
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
