apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresqldata
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  volumeName: postgresqldata-pv
  storageClassName: postgres-storage-class
