apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default
  volumeName: azurefile
  resources:
    requests:
      storage: 1Gi
