apiVersion: v1
kind: us-chirpstack-postegres-pvc
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: us-chirpstack-postegres-pv
  storageClassName: managed-csi