apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: us-chirpstack-postgres
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-nfs
  csi:
    driver: file.csi.azure.com
    volumeHandle: "PowerPlatform-IOTReporting-dev#usiotreportingdev#us-chirpstack-postgres"
    volumeAttributes:
      resourceGroup:
      shareName: us-chirpstack-postgres
    nodeStageSecretRef:
      name: azure-secret
      namespace: azurefile-csi-nfs
  mountOptions:
    - dir_mode=0750
    - file_mode=0750
    - uid=999
    - gid=999
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl 