apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage-class
provisioner: disk.csi.azure.com
parameters:
  storageaccounttype: Premium_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer