apiVersion: v1
kind: PersistentVolume
metadata:
  name: us-chirpstack-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    volumeHandle: usiotreportingdev#us-chirpstack-postgres-data
    readOnly: false
    volumeAttributes:
      storageAccount: usiotreportingdev
    readOnly: false
    nodeStageSecretRef:
      name: azure-file-secret