apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresqldata
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: private-azurefile-csi
  azureFile:
    secretName: azure-file-secret
    shareName: us-chirpstack-postgres-data
    readOnly: false
