apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: us-chirpstack-postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: us-chirpstack-postgres-pv
