apiVersion: v1
kind: PersistentVolume
metadata:
  name: us-chirpstack-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  csi:
    driver: file.csi.azure.com
    volumeHandle: "PowerPlatform-IOTReporting-dev#usiotreportingdev#us-chirpstack-postgres-data"
    volumeAttributes:
      storageAccount: usiotreportingdev
      shareName: us-chirpstack-postgres-data
    readOnly: false
    nodeStageSecretRef:
      name: azure-file-secret
      namespace: default
  mountOptions:
    - dir_mode=0750
    - file_mode=0750
    - uid=999
    - gid=999
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
