apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresqldata
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  csi:
    driver: file.csi.azure.com
    volumeHandle: "PowerPlatform-IOTReporting-dev#usiotreportingdev#us-chirpstack-postgres-data"
    volumeAttributes:
      shareName:
    nodeStageSecretRef:
      name: azure-file-secret
      namespace: default
  mountOptions:
    - dir_mode=0750
    - file_mode=0750
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
