apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: us-chirpstack-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: us-chirpstack-redis-pv
  storageClassName: managed-csi