apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: chirpstack
  name: chirpstack
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chirpstack
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: chirpstack
    spec:
      containers:
        - args:
            - -c
            - /etc/chirpstack
          env:
            - name: MQTT_BROKER_HOST
              value: mosquitto
            - name: POSTGRESQL_HOST
              value: postgresql
            - name: REDIS_HOST
              value: redis
          image: chirpstack/chirpstack:4
          name: chirpstack
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:                     # Add readiness probe to check service readiness
            httpGet:
              path: /health                   # Replace "/health" with the correct health check path
              port: 8080
            initialDelaySeconds: 10           # Delay before the first readiness check
            periodSeconds: 10                 # Check readiness every 10 seconds
            failureThreshold: 3
          livenessProbe:                      # Add liveness probe to monitor container health
            httpGet:
              path: /health                   # Replace "/health" with the correct health check path
              port: 8080
            initialDelaySeconds: 30           # Allow time for app initialization
            periodSeconds: 30
          volumeMounts:
            - mountPath: /etc/chirpstack
              name: chirpstack-cm0
            - mountPath: /opt/lorawan-devices
              name: chirpstack-cm1
      volumes:
        - name: chirpstack-cm1
          persistentVolumeClaim:
            claimName: us-chirpstack-chirpstack-pvc
        - configMap:
            name: chirpstack-cm0
          name: chirpstack-cm0
