apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: chirpstack-gateway-bridge-basicstation
  name: chirpstack-gateway-bridge-basicstation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chirpstack-gateway-bridge-basicstation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: chirpstack-gateway-bridge-basicstation
    spec:
      containers:
        - args:
            - -c
            - /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-us915_0.toml
          image: chirpstack/chirpstack-gateway-bridge:4
          name: chirpstack-gateway-bridge-basicstation
          ports:
            - containerPort: 3001
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/chirpstack-gateway-bridge
              name: chirpstack-gateway-bridge-basicstation-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: chirpstack-gateway-bridge-basicstation-cm0
          name: chirpstack-gateway-bridge-basicstation-cm0
