apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: node-red
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-red
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: node-red
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /data"]
          volumeMounts:
            - mountPath: /data
              name: node-red-data
      containers:
        - env:
            - name: NODE_RED_ENABLE_PROJECTS
              value: "true"
            - name: TZ
              value: America/New_York
            - name: NODE_RED_IP
              value: "0.0.0.0"
            - name: uiHost
              value: 0.0.0.0  
          image: nodered/node-red:latest
          name: node-red
          ports:
            - containerPort: 1880
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: node-red-data
      volumes:
        - name: node-red-data
          persistentVolumeClaim:
            claimName: us-chirpstack-nodered-pvc