apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 999
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
                echo "Fixing permissions..."
                chmod -R 0750 /var/lib/postgresql/data
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: azurefile
      containers:
        - name: postgresql
          image: postgres:14-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: root
            - name: TZ
              value: America/New_York
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: azurefile
            - mountPath: /var/run/postgresql
              name: postgresql-run
      volumes:
        - name: azurefile
          persistentVolumeClaim:
            claimName: azurefile
        - name: postgresql-run
          emptyDir: {}
