apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgres
    spec:
      initContainers:
        - name: init-postgres
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/postgresql/data/*']
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-cm1
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: root
            - name: TZ
              value: America/New_York
          image: postgres:14-alpine
          name: postgres
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-cm0
              readOnly: false
            - mountPath: /var/lib/postgresql/data
              name: postgres-cm1
              readOnly: false
      restartPolicy: Always
      volumes:
      - name: postgres-cm1
        persistentVolumeClaim:
          claimName: postgresqldata
      - name: postgres-cm0
        configMap:
          name: config-postgres
