apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgresql
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgresql
    spec:
      initContainers:
        - name: init-postgres
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/postgresql/data/*']
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresqldata
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: root
            - name: TZ
              value: America/New_York
          image: postgres:14-alpine
          name: postgres
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-cm0
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: postgresqldata
            - mountPath: /etc/postgresql
              name: config-postgres
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: postgresqldata
          persistentVolumeClaim:
            claimName: postgresqldata
        - name: postgres-cm0
          configMap:
            name: postgres-cm0
        - name: config-postgres
          configMap:
            name: postgres-cm1
