apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: postgresqldata
      mountPath: /var/lib/postgresql/data
    - name: docker-entrypoint-initdb
      mountPath: /docker-entrypoint-initdb.d
  volumes:
  - name: postgresqldata
    persistentVolumeClaim:
      claimName: postgresqldata
  - name: docker-entrypoint-initdb
    configMap:
      name: postgres-cm0
