apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.12.0-beta.0
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
  loadBalancerIP: 4.157.230.39
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chirpstack-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # If using HTTPS
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  ingressClassName: nginx  # Assumes you're using NGINX Ingress Controller
  rules:
    - host: cpmfgopschirpstack.eastus.cloudapp.azure.com # Replace with your domain
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chirpstack
                port:
                  number: 8080
  tls:
    - hosts:
        - cpmfgopschirpstack.eastus.cloudapp.azure.com  # Replace with your domain
      secretName: chirpstack-tls-secret  # Ensure you have a TLS secret for HTTPS
