apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: chirpstack-cert
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: chirpstack
    type: kubernetes.io/tls
    data:
    - objectName: chirpstack  # Specify only the certificate name
      key: tls.crt  # TLS certificate key
  parameters:
    usePodIdentity: "false"  # Change to "true" if using Managed Identity
    keyvaultName: "us-iotreporting-dev"  # Name of your Azure KeyVault
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: chirpstack  # The name of the certificate in KeyVault
          objectType: "certificate"  # This should specify it's a certificate
