apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chirpstack-ingress
  namespace: ingress-nginx  # Ensure this is the correct namespace
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"   # Automatically redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/secure-backends: "true"  # Secure the connection to your service
spec:
  ingressClassName: nginx  # Ensure this is the ingress class you're using
  rules:
    - host: 4.157.230.39   # Use your external IP address or domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chirpstack
                port:
                  number: 8080
  tls:
    - hosts:
        - 4.157.230.39  # Use your external IP or domain here
      secretName: chirpstack-tls-secret  # Refer to the TLS secret you already created
