apiVersion: v1
data:
  chirpstack.toml: |
    # Logging.
    [logging]

      # Log level.
      #
      # Options are: trace, debug, info, warn error.
      level="info"


    # PostgreSQL configuration.
    [postgresql]

      # PostgreSQL DSN.
      #
      # Format example: postgres://<USERNAME>:<PASSWORD>@<HOSTNAME>/<DATABASE>?sslmode=<SSLMODE>.
      #
      # SSL mode options:
      #  * disable - no SSL
      #  * require - Always SSL (skip verification)
      #  * verify-ca - Always SSL (verify that the certificate presented by the server was signed by a trusted CA)
      #  * verify-full - Always SSL (verify that the certification presented by the server was signed by a trusted CA and the server host name matches the one in the certificate)
      dsn="postgres://chirpstack:chirpstack@$POSTGRESQL_HOST/chirpstack?sslmode=disable"

      # Max open connections.
      #
      # This sets the max. number of open connections that are allowed in the
      # PostgreSQL connection pool.
      max_open_connections=10

      # Min idle connections.
      #
      # This sets the min. number of idle connections in the PostgreSQL connection
      # pool (0 = equal to max_open_connections).
      min_idle_connections=0


    # Redis configuration.
    [redis]

      # Server address or addresses.
      #
      # Set multiple addresses when connecting to a cluster.
      servers=[
        "redis://$REDIS_HOST/",
      ]

      # TLS enabled.
      tls_enabled=false

      # Redis Cluster.
      #
      # Set this to true when the provided URLs are pointing to a Redis Cluster
      # instance.
      cluster=false


    # Network related configuration.
    [network]

      # Network identifier (NetID, 3 bytes) encoded as HEX (e.g. 010203).
      net_id="000000"

      # Enabled regions.
      #
      # Multiple regions can be enabled simultaneously. Each region must match
      # the 'name' parameter of the region configuration in '[[regions]]'.
      enabled_regions=[
        "as923",
        "as923_2",
        "as923_3",
        "as923_4",
        "au915_0",
        "cn470_10",
        "cn779",
        "eu433",
        "eu868",
        "in865",
        "ism2400",
        "kr920",
        "ru864",
        "us915_0",
        "us915_1",
      ]


    # API interface configuration.
    [api]

      # interface:port to bind the API interface to.
      bind="0.0.0.0:8080"

      # Secret.
      #
      # This secret is used for generating login and API tokens, make sure this
      # is never exposed. Changing this secret will invalidate all login and API
      # tokens. The following command can be used to generate a random secret:
      #   openssl rand -base64 32
      secret="you-must-replace-this"


    [integration]
      enabled=["mqtt"]

      [integration.mqtt]
        server="tcp://$MQTT_BROKER_HOST:1883/"
        json=true
  
  region_us915_0.toml: "# This file contains an example US915 example (channels 0-7 + 64).\n[[regions]]\n\n  # ID is an use-defined identifier for this region.\n  id=\"us915_0\"\n\n  # Description is a short description for this region.\n  description=\"US915 (channels 0-7 + 64)\"\n\n  # Common-name refers to the common-name of this region as defined by\n  # the LoRa Alliance.\n  common_name=\"US915\"\n\n\n  # Gateway configuration.\n  [regions.gateway]\n\n    # Force gateways as private.\n    #\n    # If enabled, gateways can only be used by devices under the same tenant.\n    force_gws_private=false\n\n    \n    # Gateway backend configuration.\n    [regions.gateway.backend]\n\n      # The enabled backend type.\n      enabled=\"mqtt\"\n\n      # MQTT configuration.\n      [regions.gateway.backend.mqtt]\n\n        # Topic prefix.\n        #\n        # The topic prefix can be used to define the region of the gateway.\n        # Note, there is no need to add a trailing '/' to the prefix. The trailing\n        # '/' is automatically added to the prefix if it is configured.\n        topic_prefix=\"us915_0\"\n\n        # MQTT server (e.g. scheme://host:port where scheme is tcp, ssl or ws)\n        server=\"tcp://$MQTT_BROKER_HOST:1883\"\n\n        # Connect with the given username (optional)\n        username=\"\"\n\n        # Connect with the given password (optional)\n        password=\"\"\n\n        # Quality of service level\n        #\n        # 0: at most once\n        # 1: at least once\n        # 2: exactly once\n        #\n        # Note: an increase of this value will decrease the performance.\n        # For more information: https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels\n        qos=0\n\n        # Clean session\n        #\n        # Set the \"clean session\" flag in the connect message when this client\n        # connects to an MQTT broker. By setting this flag you are indicating\n        # that no messages saved by the broker for this client should be delivered.\n        clean_session=false\n\n        # Client ID\n        #\n        # Set the client id to be used by this client when connecting to the MQTT\n        # broker. A client id must be no longer than 23 characters. If left blank,\n        # a random id will be generated by ChirpStack.\n        client_id=\"\"\n\n        # Keep alive interval.\n        #\n        # This defines the maximum time that that should pass without communication\n        # between the client and server.\n        keep_alive_interval=\"30s\"\n\n        # CA certificate file (optional)\n        #\n        # Use this when setting up a secure connection (when server uses ssl://...)\n        # but the certificate used by the server is not trusted by any CA certificate\n        # on the server (e.g. when self generated).\n        ca_cert=\"\"\n\n        # TLS certificate file (optional)\n        tls_cert=\"\"\n\n        # TLS key file (optional)\n        tls_key=\"\"\n\n\n    # Gateway channel configuration.\n    #\n    # Note: this configuration is only used in case the gateway is using the\n    # ChirpStack Concentratord daemon. In any other case, this configuration \n    # is ignored.\n    [[regions.gateway.channels]]\n      frequency=902300000\n      bandwidth=125000\n      modulation=\"LORA\"\n      spreading_factors=[7, 8, 9, 10]\n\n    [[regions.gateway.channels]]\n      frequency=902500000\n      bandwidth=125000\n      modulation=\"LORA\"\n      spreading_factors=[7, 8, 9, 10]\n\n    [[regions.gateway.channels]]\n      frequency=902700000\n      bandwidth=125000\n      modulation=\"LORA\"\n      spreading_factors=[7, 8, 9, 10]\n\n    [[regions.gateway.channels]]\n      frequency=902900000\n      bandwidth=125000\n      modulation=\"LORA\"\n      spreading_factors=[7, 8, 9, 10]\n\n    [[regions.gateway.channels]]\n      frequency=903100000\n      bandwidth=125000\n      modulation=\"LORA\"\n      spreading_factors=[7, 8, 9, 10]\n\n    [[regions.gateway.channels]]\n      frequency=903300000\n      bandwidth=125000\n      modulation=\"LORA\"\n      spreading_factors=[7, 8, 9, 10]\n\n    [[regions.gateway.channels]]\n      frequency=903500000\n      bandwidth=125000\n      modulation=\"LORA\"\n      spreading_factors=[7, 8, 9, 10]\n\n    [[regions.gateway.channels]]\n      frequency=903700000\n      bandwidth=125000\n      modulation=\"LORA\"\n      spreading_factors=[7, 8, 9, 10]\n\n    [[regions.gateway.channels]]\n      frequency=903000000\n      bandwidth=500000\n      modulation=\"LORA\"\n      spreading_factors=[8]\n\n\n  # Region specific network configuration.\n  [regions.network]\n    \n    # Installation margin (dB) used by the ADR engine.\n    #\n    # A higher number means that the network-server will keep more margin,\n    # resulting in a lower data-rate but decreasing the chance that the\n    # device gets disconnected because it is unable to reach one of the\n    # surrounded gateways.\n    installation_margin=10\n\n    # RX window (Class-A).\n    #\n    # Set this to:\n    # 0: RX1 / RX2\n    # 1: RX1 only\n    # 2: RX2 only\n    rx_window=0\n\n    # RX1 delay (1 - 15 seconds).\n    rx1_delay=1\n\n    # RX1 data-rate offset\n    rx1_dr_offset=0\n\n    # RX2 data-rate\n    rx2_dr=8\n\n    # RX2 frequency (Hz)\n    rx2_frequency=923300000\n\n    # Prefer RX2 on RX1 data-rate less than.\n    #\n    # Prefer RX2 over RX1 based on the RX1 data-rate. When the RX1 data-rate\n    # is smaller than the configured value, then the Network Server will\n    # first try to schedule the downlink for RX2, failing that (e.g. the gateway\n    # has already a payload scheduled at the RX2 timing) it will try RX1.\n    rx2_prefer_on_rx1_dr_lt=0\n\n    # Prefer RX2 on link budget.\n    #\n    # When the link-budget is better for RX2 than for RX1, the Network Server will first\n    # try to schedule the downlink in RX2, failing that it will try RX1.\n    rx2_prefer_on_link_budget=false\n\n    # Downlink TX Power (dBm)\n    #\n    # When set to -1, the downlink TX Power from the configured band will\n    # be used.\n    #\n    # Please consult the LoRaWAN Regional Parameters and local regulations\n    # for valid and legal options. Note that the configured TX Power must be\n    # supported by your gateway(s).\n    downlink_tx_power=-1\n\n    # ADR is disabled.\n    adr_disabled=false\n\n    # Minimum data-rate.\n    min_dr=0\n\n    # Maximum data-rate.\n    max_dr=3\n\n    # Enabled uplink channels.\n    #\n    # Use this when ony a sub-set of the by default enabled channels are being\n    # used. For example when only using the first 8 channels of the US band.\n    # Note: when left blank / empty array, all channels will be enabled.\n    enabled_uplink_channels=[0, 1, 2, 3, 4, 5, 6, 7, 64]\n\n\n    # Rejoin-request configuration (LoRaWAN 1.1)\n    [regions.network.rejoin_request]\n\n      # Request devices to periodically send rejoin-requests.\n      enabled=false\n\n      # The device must send a rejoin-request type 0 at least every 2^(max_count_n + 4)\n      # uplink messages. Valid values are 0 to 15.\n      max_count_n=0\n\n      # The device must send a rejoin-request type 0 at least every 2^(max_time_n + 10)\n      # seconds. Valid values are 0 to 15.\n      #\n      # 0  = roughly 17 minutes\n      # 15 = about 1 year\n      max_time_n=0\n    \n\n    # Class-B configuration.\n    [regions.network.class_b]\n\n      # Ping-slot data-rate. \n      ping_slot_dr=8\n\n      # Ping-slot frequency (Hz)\n      #\n      # set this to 0 to use the default frequency plan for the configured region\n      # (which could be frequency hopping).\n      ping_slot_frequency=0\n"

kind: ConfigMap
metadata:
  labels:
    io.kompose.service: chirpstack
  name: chirpstack-cm0
