apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: carlenkaiser@ccimail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
          ingressTemplate:
            metadata:
              name: cm-acme-http-solver
              annotations:
                kubernetes.io/ingress.class: "nginx"
            spec:
              rules:
              - host: "your-domain.com"  # Replace with your domain
                http:
                  paths:
                  - path: "/.well-known/acme-challenge/"
                    pathType: Prefix
                    backend:
                      service:
                        name: cm-acme-http-solver  # Solver service name
                        port:
                          number: 8089  # Static port for the challenge solver
